/**
 * The landing page contract — what the platform reads out of authored HTML.
 *
 * ── WHY A CONTRACT AND NOT A SLOT VOCABULARY ────────────────────────────────
 *
 * `StorefrontTemplate` uses a fixed `SLOT_KEYS` list, and that is right for a
 * catalogue: twelve slots cover every shop, and content is portable between
 * designs. It is wrong here. A landing page's persuasion structure is bespoke
 * per campaign — one wants a comparison table, the next a doctor's testimonial,
 * the next a countdown and nothing else — so a fixed list either grows to a
 * hundred entries or becomes a straitjacket.
 *
 * So there is no slot list, no template registry and no React component per
 * design. The page is HTML; this module reads a small set of `data-hisaab-*`
 * markers out of it and derives the editor from what it finds. Any design works
 * — including one generated by a language model — provided the markers are
 * present.
 *
 * ── TWO OUTPUTS, AND THEY ANSWER DIFFERENT QUESTIONS ────────────────────────
 *
 *   parseContract()    what IS in this HTML — the manifest the editor renders,
 *                      the form's shape, and the media URLs the I-18 reconciler
 *                      needs.
 *   validateContract() whether it can take an order — the publish-time gate.
 *
 * The second is the one that matters most. A page that publishes and then
 * silently cannot accept an order is the worst outcome this feature has: the
 * shop is paying for advertisements pointing at it.
 *
 * ── THIS MODULE READS. IT NEVER TRUSTS. ─────────────────────────────────────
 *
 * Nothing here extracts a price. `data-hisaab="offer-price"` nodes are OUTPUTS
 * that the public runtime writes into from `LandingPage.offers[]`; a number
 * typed into the HTML is decorative and is overwritten before first paint
 * (I-13). If a future change makes this file read a value that ends up on an
 * order, that invariant has been broken.
 */

const { Parser } = require('htmlparser2');

/** Editable-content markers. The key after the `=` is arbitrary and author-chosen. */
const CONTENT_MARKERS = Object.freeze({
  'data-hisaab-edit': 'text',
  'data-hisaab-rich': 'rich',
  'data-hisaab-img': 'image',
  'data-hisaab-href': 'link',
  'data-hisaab-repeat': 'repeat',
  'data-hisaab-show': 'toggle',
});

/** Groups the derived editor renders under. Inherited from the nearest ancestor. */
const GROUP_MARKER = 'data-hisaab-group';

/**
 * Form field names. FIXED — the public runtime binds to exactly these.
 *
 * They are `name` attributes rather than `data-*` markers because a form field
 * already has a name, and inventing a parallel identifier for it would mean an
 * author could set the two to different things.
 */
const REQUIRED_FIELDS = Object.freeze(['customerName', 'phone', 'address']);
const OPTIONAL_FIELDS = Object.freeze([
  'note', 'quantity', 'offer', 'zone',
  // Checkout options. Optional individually, but conditionally REQUIRED by the
  // page's own configuration — a page that offers advance payment and has no
  // `trxId` box collects a payment nobody can trace, and that check is in
  // `validateContract` rather than here because it depends on the config, not
  // on the markup.
  'paymentMethod', 'trxId', 'senderNumber', 'coupon',
]);
const ALL_FIELDS = Object.freeze([...REQUIRED_FIELDS, ...OPTIONAL_FIELDS]);

/**
 * `data-hisaab="..."` roles. Structural, not content.
 *
 * Everything except `order-form` and `submit` is an OUTPUT: the runtime writes
 * into it and never reads from it. See the header.
 */
const ROLES = Object.freeze([
  'order-form',
  'submit',
  'offer-price',
  'subtotal',
  'delivery-charge',
  'total',
  'error',
  'success',
]);

/** How much text to keep as a preview label in the editor. */
const PREVIEW_LIMIT = 80;

/**
 * Read an HTML document's contract.
 *
 * One linear pass with a small stack — no DOM is built, because the only
 * hierarchy that matters is "which group am I inside" and "am I inside the
 * form", both of which a stack answers.
 *
 * @param {string} html  as stored — a whole document or a fragment, either way
 * @returns {{
 *   manifest: Array,
 *   form: { present: boolean, fields: Object, roles: Object },
 *   offerKeys: string[],
 *   zoneKeys: string[],
 *   mediaUrls: string[],
 *   duplicateKeys: string[]
 * }}
 */
function parseContract(html) {
  const manifest = [];
  const seenKeys = new Map();
  const duplicateKeys = [];

  const form = { present: false, fields: {}, roles: {} };
  const offerKeys = new Set();
  const zoneKeys = new Set();
  const mediaUrls = new Set();

  /** Open-element stack: group inheritance, form nesting, text collection. */
  const stack = [];
  // Which manifest entries are currently collecting text, innermost last.
  const collecting = [];
  let formDepth = 0;
  // Name of the <select> currently open, so its <option value=> can be attributed.
  let openSelect = null;

  const parser = new Parser({
    onopentag(name, attribs) {
      const parentGroup = stack.length ? stack[stack.length - 1].group : null;
      const group = attribs[GROUP_MARKER] ? String(attribs[GROUP_MARKER]).trim() : parentGroup;

      const frame = { name, group, entries: [] };

      // ── Content markers ──────────────────────────────────────────────
      for (const [attr, kind] of Object.entries(CONTENT_MARKERS)) {
        const raw = attribs[attr];
        if (raw === undefined) continue;

        const key = String(raw).trim();
        if (!key) continue;

        if (seenKeys.has(key)) {
          // Two elements claiming one key means editing either one writes to
          // both, which reads as a bug the first time an author notices it.
          // Recorded rather than thrown: the page still renders, and the save
          // response names it.
          duplicateKeys.push(key);
        } else {
          seenKeys.set(key, kind);
        }

        const entry = { key, kind, group: group || null, tag: name, preview: '' };
        manifest.push(entry);
        frame.entries.push(entry);

        // Only text-bearing kinds accumulate a preview.
        if (kind === 'text' || kind === 'rich') collecting.push(entry);
      }

      // ── Structural roles ─────────────────────────────────────────────
      const role = attribs['data-hisaab'];
      if (role) {
        const r = String(role).trim();
        form.roles[r] = (form.roles[r] || 0) + 1;
        if (r === 'order-form') form.present = true;
      }

      if (name === 'form') formDepth += 1;

      // ── Form fields ──────────────────────────────────────────────────
      if (['input', 'select', 'textarea'].includes(name) && attribs.name) {
        const field = String(attribs.name).trim();
        if (ALL_FIELDS.includes(field)) {
          const existing = form.fields[field] || { tags: [], types: new Set(), values: new Set(), required: false, inForm: false };
          existing.tags.push(name);
          if (attribs.type) existing.types.add(String(attribs.type).toLowerCase());
          if (attribs.required !== undefined) existing.required = true;
          // Whether the field is INSIDE the form matters: a stray input outside
          // it is never submitted, and the page would fail only at order time.
          if (formDepth > 0) existing.inForm = true;
          if (attribs.value !== undefined) existing.values.add(String(attribs.value));
          form.fields[field] = existing;
        }
        if (name === 'select') openSelect = field;
      }

      // `<option value>` belongs to whichever select is open.
      if (name === 'option' && openSelect && attribs.value !== undefined) {
        const target = form.fields[openSelect];
        if (target) target.values.add(String(attribs.value));
      }

      // ── Offer and zone values ────────────────────────────────────────
      if (attribs['data-offer-key']) offerKeys.add(String(attribs['data-offer-key']).trim());
      if (attribs.name === 'offer' && attribs.value !== undefined) offerKeys.add(String(attribs.value));
      if (attribs.name === 'zone' && attribs.value !== undefined) zoneKeys.add(String(attribs.value));
      if (name === 'option' && openSelect === 'offer' && attribs.value) offerKeys.add(String(attribs.value));
      if (name === 'option' && openSelect === 'zone' && attribs.value) zoneKeys.add(String(attribs.value));

      // ── Media URLs, for the I-18 reconciler ──────────────────────────
      // Every URL the document points at, whoever put it there. The consumer's
      // obligation under I-18 is to find the ones an author pasted by hand, and
      // those look exactly like the ones a picker inserted.
      for (const attr of ['src', 'poster', 'href']) {
        if (attribs[attr]) mediaUrls.add(String(attribs[attr]));
      }
      if (attribs.srcset) {
        for (const part of String(attribs.srcset).split(',')) {
          const url = part.trim().split(/\s+/)[0];
          if (url) mediaUrls.add(url);
        }
      }

      stack.push(frame);
    },

    ontext(text) {
      if (collecting.length === 0) return;
      const trimmed = String(text).replace(/\s+/g, ' ');
      if (!trimmed.trim()) return;
      // Every open collector gets the text, so a marked wrapper shows the same
      // preview a reader would see.
      for (const entry of collecting) {
        if (entry.preview.length < PREVIEW_LIMIT) {
          entry.preview = `${entry.preview}${trimmed}`.slice(0, PREVIEW_LIMIT);
        }
      }
    },

    onclosetag(name) {
      const frame = stack.pop();
      if (name === 'form' && formDepth > 0) formDepth -= 1;
      if (name === 'select') openSelect = null;

      for (const entry of frame?.entries || []) {
        const at = collecting.indexOf(entry);
        if (at !== -1) collecting.splice(at, 1);
        entry.preview = entry.preview.trim();
      }
    },
  }, {
    // Landing pages are HTML, not XML: void elements have no closing tag and
    // attribute names are case-insensitive.
    lowerCaseTags: true,
    lowerCaseAttributeNames: true,
    recognizeSelfClosing: true,
  });

  parser.write(String(html || ''));
  parser.end();

  // Sets are an implementation detail; callers want plain data.
  for (const field of Object.values(form.fields)) {
    field.types = [...field.types];
    field.values = [...field.values];
  }

  return {
    manifest,
    form,
    offerKeys: [...offerKeys],
    zoneKeys: [...zoneKeys],
    mediaUrls: [...mediaUrls],
    duplicateKeys: [...new Set(duplicateKeys)],
  };
}

/**
 * Can this page take an order?
 *
 * The publish-time gate. Returns issues rather than throwing, so the save
 * response can list everything wrong at once — an author fixing one problem per
 * round trip against generated HTML is how an afternoon disappears.
 *
 * Each issue carries `severity`:
 *   'error' — publishing is refused. The page cannot take an order.
 *   'warn'  — publishing proceeds. Something is odd but not broken.
 *
 * @param {Object} parsed  from `parseContract`
 * @param {Object} page    the LandingPage, for offer and zone keys
 */
function validateContract(parsed, page = {}) {
  const issues = [];
  const add = (severity, code, en, bn) => issues.push({ severity, code, message: en, messageBn: bn });

  // ── The form must exist ───────────────────────────────────────────────
  if (!parsed.form.present) {
    add('error', 'NO_FORM',
      'No element carries data-hisaab="order-form"',
      'অর্ডার ফর্ম পাওয়া যায়নি — কোনো এলিমেন্টে data-hisaab="order-form" নেই');
    // Everything below is about the form's contents; without one they would be
    // a page of noise on top of the real problem.
    return issues;
  }

  if ((parsed.form.roles['order-form'] || 0) > 1) {
    add('error', 'MULTIPLE_FORMS',
      'More than one element is marked as the order form',
      'একাধিক এলিমেন্টে data-hisaab="order-form" আছে — একটাই থাকতে পারবে');
  }

  // ── Required fields ───────────────────────────────────────────────────
  for (const field of REQUIRED_FIELDS) {
    const found = parsed.form.fields[field];
    if (!found) {
      add('error', `MISSING_FIELD_${field}`,
        `The form has no field named "${field}"`,
        `ফর্মে "${field}" নামের ঘর নেই`);
    } else if (!found.inForm) {
      // The subtle one: the field exists, the page looks right, and the value
      // is never submitted because it sits outside the form element.
      add('error', `FIELD_OUTSIDE_FORM_${field}`,
        `Field "${field}" is outside the order form and would never be submitted`,
        `"${field}" ঘরটি অর্ডার ফর্মের বাইরে আছে — এটি কখনো জমা হবে না`);
    }
  }

  // ── Submit ────────────────────────────────────────────────────────────
  if (!parsed.form.roles.submit) {
    add('error', 'NO_SUBMIT',
      'No element carries data-hisaab="submit"',
      'সাবমিট বোতাম পাওয়া যায়নি — কোনো এলিমেন্টে data-hisaab="submit" নেই');
  }

  // ── Offers ────────────────────────────────────────────────────────────
  const offers = (page.offers || []).filter((o) => o.isActive !== false);
  const known = new Set(offers.map((o) => String(o.key)));

  if (offers.length === 0) {
    add('error', 'NO_OFFERS',
      'The page has no active offers, so there is nothing to order',
      'পেজে কোনো সক্রিয় অফার নেই — অর্ডার করার মতো কিছু নেই');
  } else if (offers.length > 1 && !parsed.form.fields.offer) {
    // One offer needs no picker; several without one means the customer cannot
    // choose, and the server would have to guess which they meant.
    add('error', 'NO_OFFER_INPUT',
      `The page has ${offers.length} offers but the form has no field named "offer"`,
      `পেজে ${offers.length}টি অফার আছে কিন্তু ফর্মে "offer" নামের ঘর নেই`);
  }

  const unknown = parsed.offerKeys.filter((k) => k && !known.has(k));
  if (unknown.length > 0) {
    add('error', 'UNKNOWN_OFFER_KEY',
      `The HTML offers keys that do not exist: ${unknown.join(', ')}`,
      `HTML-এ এমন অফার আছে যা কনফিগে নেই: ${unknown.join(', ')}`);
  }

  const unoffered = [...known].filter((k) => !parsed.offerKeys.includes(k));
  if (unoffered.length > 0 && parsed.form.fields.offer) {
    // Not an error: an offer configured but not shown is a draft the admin has
    // not wired up yet, and refusing would block a page that works.
    add('warn', 'OFFER_NOT_IN_HTML',
      `Configured offers not present in the HTML: ${unoffered.join(', ')}`,
      `কনফিগে আছে কিন্তু পেজে দেখানো হচ্ছে না: ${unoffered.join(', ')}`);
  }

  // ── Zones ─────────────────────────────────────────────────────────────
  const zones = (page.delivery?.zones || []).filter((z) => z.isActive !== false);
  const knownZones = new Set(zones.map((z) => String(z.key)));
  const unknownZones = parsed.zoneKeys.filter((k) => k && !knownZones.has(k));
  if (unknownZones.length > 0) {
    add('error', 'UNKNOWN_ZONE_KEY',
      `The HTML offers delivery zones that do not exist: ${unknownZones.join(', ')}`,
      `HTML-এ এমন ডেলিভারি এলাকা আছে যা কনফিগে নেই: ${unknownZones.join(', ')}`);
  }
  if (zones.length > 1 && !parsed.form.fields.zone) {
    add('warn', 'NO_ZONE_INPUT',
      `${zones.length} delivery zones are configured but the form has no "zone" field — the first will always be used`,
      `${zones.length}টি ডেলিভারি এলাকা কনফিগ করা আছে কিন্তু ফর্মে "zone" ঘর নেই — সবসময় প্রথমটিই ধরা হবে`);
  }

  // ── Payment ───────────────────────────────────────────────────────────
  //
  // Every check here is conditional on the page's CONFIG rather than on the
  // markup, which is why it cannot live in the parser. A page that takes cash
  // on delivery needs none of these fields and must not be nagged about them.
  const methods = (page.payment?.methods || []).filter(Boolean);
  if (methods.includes('advance')) {
    if (!parsed.form.fields.trxId) {
      // An error, not a warning: the order goes through, the shop is told money
      // was sent, and there is no reference to check it against. The customer is
      // then asked for a TrxID on the phone, which is the support call this
      // whole feature was meant to avoid.
      add('error', 'ADVANCE_NO_TRXID',
        'Advance payment is enabled but the form has no field named "trxId"',
        'অগ্রিম পেমেন্ট চালু আছে কিন্তু ফর্মে "trxId" নামের ঘর নেই');
    }
    if (methods.length > 1 && !parsed.form.fields.paymentMethod) {
      add('error', 'NO_PAYMENT_INPUT',
        'The page offers more than one payment method but the form has no field named "paymentMethod"',
        'একাধিক পেমেন্ট পদ্ধতি চালু আছে কিন্তু ফর্মে "paymentMethod" নামের ঘর নেই');
    }
    if (!page.payment?.advanceInstructions) {
      // A warning: the page may well print the bKash number in its own copy.
      add('warn', 'ADVANCE_NO_INSTRUCTIONS',
        'Advance payment is enabled but no instructions are configured — the customer is not told where to send the money',
        'অগ্রিম পেমেন্ট চালু আছে কিন্তু নির্দেশনা লেখা নেই — কাস্টমার জানবে না কোথায় টাকা পাঠাবে');
    }
    if ((page.payment?.advanceMode || 'delivery') === 'fixed' && !(page.payment?.advanceAmount > 0)) {
      add('error', 'ADVANCE_NO_AMOUNT',
        'Advance payment is set to a fixed amount, but that amount is zero',
        'অগ্রিম পেমেন্ট "নির্দিষ্ট পরিমাণ" মোডে আছে কিন্তু পরিমাণ ০ দেওয়া');
    }
  }

  // ── Coupons ───────────────────────────────────────────────────────────
  if ((page.coupons || []).some((c) => c.isActive !== false) && !parsed.form.fields.coupon) {
    // A warning rather than an error: the codes may be for a later week of the
    // campaign, and a configured-but-unreachable code costs nobody an order.
    add('warn', 'NO_COUPON_INPUT',
      'Active coupons are configured but the form has no field named "coupon" — nobody can use them',
      'সক্রিয় কুপন আছে কিন্তু ফর্মে "coupon" নামের ঘর নেই — কেউ ব্যবহার করতে পারবে না');
  }

  // ── Duplicates ────────────────────────────────────────────────────────
  if (parsed.duplicateKeys.length > 0) {
    add('warn', 'DUPLICATE_KEYS',
      `These editor keys appear more than once: ${parsed.duplicateKeys.join(', ')}`,
      `এই কী-গুলো একাধিকবার ব্যবহৃত হয়েছে: ${parsed.duplicateKeys.join(', ')}`);
  }

  // ── Success panel ─────────────────────────────────────────────────────
  if (!parsed.form.roles.success) {
    add('warn', 'NO_SUCCESS_PANEL',
      'No element carries data-hisaab="success" — the customer sees no confirmation after ordering',
      'data-hisaab="success" নেই — অর্ডারের পর কাস্টমার কোনো নিশ্চিতকরণ দেখবে না');
  }

  return issues;
}

/** Does this issue list block publication? */
function hasBlockingIssues(issues) {
  return (issues || []).some((i) => i.severity === 'error');
}

module.exports = {
  parseContract,
  validateContract,
  hasBlockingIssues,
  CONTENT_MARKERS,
  GROUP_MARKER,
  REQUIRED_FIELDS,
  OPTIONAL_FIELDS,
  ALL_FIELDS,
  ROLES,
  PREVIEW_LIMIT,
};
